# Generated by Django 5.2.17 on 2026-08-23 13:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_follow_ups'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_email', models.EmailField(max_length=254)),
                ('refresh_token_encrypted', models.BinaryField()),
                ('key_version', models.PositiveSmallIntegerField(help_text='Which GMAIL_TOKEN_KEY version encrypted this row.')),
                ('access_token_encrypted', models.BinaryField(blank=True, null=True)),
                ('access_token_key_version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_scopes', models.JSONField(blank=True, default=list)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('identity_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_credential', to='crm.teammember')),
            ],
            options={
                'db_table': 'gmail_credentials',
            },
        ),
    ]
