# Generated by Django 5.2.17 on 2026-09-01 12:48

"""Help text only -- no column changes.

`footer_is_html` said "Leads only", and that sentence sat next to the checkbox
on the form. Opening the checkbox to every member without this would leave the
one member who could finally use it being told they could not.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_revoke_api_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='footer_is_html',
            field=models.BooleanField(default=False, help_text='Paste the signature you already use. Off, tags go out as visible text.'),
        ),
    ]
